### PR TITLE
Revert "Rename has_key? -> key? (BC compatible)"

### PR DESCRIPTION
**Pull request by jdmundrawala**
This reverts commit d4548e5c898a032c6751e25734371213a1b165c9.

Fixes https://github.com/chef/chef/issues/3365

cc @chef/client-core

### CODE REVIEW

**Comment by danielsdeleo** [comment]
Sad face, but yeah, :+1:

**Comment by tyler-ball** [comment]
:+1:

**Comment by lamont-granquist** [comment]
:+1:

**Comment by lamont-granquist** [comment]
Do we need to do a release?

**Comment by jdmundrawala** [comment]
yep, release needed

**Pull request merged**
